- lib/payments/stripe.ts
Spotted it while randomly browsing the code. This is to avoid the rest of the function to be executed.
> fix(stripe): add missing return

- app/(dashboard)/dashboard/layout.tsx
- app/(dashboard)/layout.tsx
- app/(dashboard)/page.tsx
Short PR to remove duplicate HTML and body tags from the dashboard layout (8f529bca7f253ec7bd97441278fe52ba2773e2dc), as they are already present in `app/layout.tsx`.
https://github.com/gumroad/shortest/blob/9b117cce076c7057501e1fd14b36779c55d45b4f/app/layout.tsx#L21-L28
It also includes minor refactoring:
- ec980346abb8ad6c4bb7c346a9244d93b8f88f7f Moves logo into it's own component for consistency if/when updated.
- 96c0c77a3f7f3bf946b47f743b271e4b0eec885d Adjusted `main` elements to match content with the html/body removal.
> Remove duplicate HTML/body tags

- app/(dashboard)/dashboard/pull-request.test.tsx
- app/(dashboard)/dashboard/pull-request.tsx
- app/api/generate-tests/route.ts
- lib/github.ts
Following the issue https://github.com/gumroad/shortest/issues/35
This will only pass failing test files to AI to update the tests to ensure a successful build.
> Only pass failing spec files to AI for updating tests

- app/(dashboard)/dashboard/page.tsx
- app/(dashboard)/dashboard/pull-request-filter.tsx
Sometimes, it takes longer than I want to review my pull requests, especially when I need to look at certain repositories. This update aims to make it quicker and easier to find my PRs.
This update adds simple filters to the frontend. Users can filter PRs by repository and build status. This helps narrow down the list, so it’s easier to focus on what matters. Specifically:
1. Repository Filter: See PRs from selected repositories.
2. Build Status Filter: Filter PRs by build status (e.g., success, failure, pending).
These filters make it easier to find PRs without adding extra complexity. This makes the review process smoother and quicker.
This update does not include advanced features like sorting by multiple criteria, keyword searches, or backend changes. The goal is to keep it simple. …
> feat: basic filtering

- README.md
- package.json
- packages/shortest/src/cli/bin.ts
Quick fix for command line args when identifying test files.
Remove prerequisite instructions from README file as that step is now shipped with shortest package.
> Fix Cli command args and update README

- .env.example
- .gitignore
- README.md
- app/__tests__/home.test.ts
- app/__tests__/login.test.ts
- lib/setup.ts
- packages/shortest/package.json
- packages/shortest/scripts/test-ai.ts
- packages/shortest/scripts/test-browser.ts
- packages/shortest/scripts/test-github.ts
- packages/shortest/src/ai/ai.ts
- packages/shortest/src/ai/prompts.ts
- packages/shortest/src/browser-use/browser.ts
- packages/shortest/src/browser-use/types.ts
- packages/shortest/src/cli/bin.ts
- packages/shortest/src/core/browser-manager.ts
- packages/shortest/src/core/executor.ts
- packages/shortest/src/tools/github.ts
- packages/shortest/src/types/index.ts
- pnpm-lock.yaml
Issue #69: This PR adds a feature to test Login functionality with Github OAuth. Devs need to add shortest as their OTP provider in their Github settings. Then shortest can act on behalf of devs to test the MFA flow using Authenticator app. 
Updates: 
1. Add Github OTP Code generation
2. Add Github login tool for AI to use to login to the web app
3. Add default caching mechanism to save the users session on the following test cases  
4. Add clear cache tool for AI to use to reset user session. (AI will use this if users are specifically testing a login flow" 
5. Add new shortest flag to add TOTP secret and generate TOTP code manually if needed: `shortest --github-code --secret=<TOTP_SECRET>`
6. Update setup script to add TOTP secret to .env
> Feat: Github Login Flow with MFA 

- packages/shortest/scripts/test-loop.ts
Small error in test-loop.ts caused the build to fail in Vercel. This should fix that.
> Fix BrowserTool instantiation in test script

- .github/workflows/publish.yml
This PR adds a new workflow for publishing new versions of shortest to npm registry. 
1. Create NPM token
2. Add to GitHub Secrets: 
Go to repo Settings > Secrets and variables > Actions 
Add new secret named NPM_TOKEN with the token value
> Feature: Github workflow for npm publishing

- .github/workflows/publish.yml
Publish workflow failed because of pnpm version mismatch
> fix pnpm version mismatch

- .github/workflows/shortest.yml
- README.md
- package.json
- packages/shortest/CHANGELOG.md
- packages/shortest/README.md
- packages/shortest/index.d.ts
- packages/shortest/package.json
- packages/shortest/src/ai/prompts/index.ts
- packages/shortest/src/browser/core/browser-tool.ts
- packages/shortest/src/browser/manager/index.ts
- packages/shortest/src/cli/setup.ts
- packages/shortest/src/core/runner/index.ts
- packages/shortest/src/index.ts
- packages/shortest/src/types/test.ts
- packages/shortest/src/utils/logger.ts
- packages/shortest/tests/test-ai.ts
- pnpm-lock.yaml
Addresses Issue: https://github.com/anti-work/iffy/issues/225 
This PR ships v0.0.8 and completes migrating Iffy from playwright test to shortest.
- Added support for playwright's browser and playwright object model 
- Rename test namespace to shortest 
- Added new lifecycle method called .after() that will only run after the specific test case
- Updated shortest.yml
> Feat: API refinement and API validation support

- packages/shortest/src/browser/manager/index.ts
I figured it makes sense that, page.goto, should allow for relative paths like "/dashboard" instead of having to define the full url. It assumes that relative paths are using the baseUrl defined in the config.
> feat: add baseURL configuration to BrowserManager context

- README.md
What:
The readme has no CLI example.
Why:
Its hard for users to understand how to setup shortest with CLI, especially if they have no technical experience doing this prior.
> Updated reame with CLI example

- packages/shortest/src/browser/integrations/mailosaur.ts
Help identify when the test execution error is related to fetching data from Mailosaur API.
> Improve debugging Mailosaur API errors

- .gitignore
- README.md
- lib/db/drizzle.ts
- package.json
- packages/shortest/CONTRIBUTING.md
- packages/shortest/src/browser/integrations/github.ts
- packages/shortest/src/index.ts
* Use `cli:` as prefix for CLI-specific scripts
* Update CONTRIBUTING
* Add support back for `.env` for the CLI (removed in https://github.com/anti-work/shortest/pull/273)
`pkg` is too generic. Using `cli` is more intuitive that the scripts are associated with the CLI tool.
> chore(cli): Rename `pkg` prefix to `cli` and improve docs

- .github/workflows/shortest.yml
- packages/shortest/src/core/runner/index.ts
Noticed on Iffy that the test failures didn't return proper status code, and the CI step didn't fail
> fix(cli): Propagate failures around parsing AI response

- README.md
- package.json
Is currently broken, see https://github.com/anti-work/shortest/issues/276
> chore(cli): Remove `cli:test:src` script

- packages/shortest/src/cache/cache.ts
- packages/shortest/src/core/runner/index.ts
- packages/shortest/src/core/runner/test-reporter.ts
`TestReporter` (formerly `Logger`) is actually **aggregating test results** (passed/failed, token usage, summary stats, etc), rather than writing logs.
Extracted from a WIP PR that will introduce `Log`, a lower-level logging system that will handle text output, color-coding, grouping, etc.
> chore(refactor): rename Logger to TestReporter

- packages/shortest/package.json
- packages/shortest/src/cli/bin.ts
- packages/shortest/src/utils/config.ts
Before this change, any errors were supressed from being rendered because the main logger uses `—-log-level=silent` by default.
> fix: expose runner errors

- packages/shortest/src/ai/client.ts
- packages/shortest/src/browser/core/api-request.ts
- packages/shortest/src/browser/core/browser-tool.ts
- packages/shortest/src/core/runner/index.ts
- packages/shortest/src/log/output.ts
- packages/shortest/src/utils/errors.ts
- packages/shortest/tests/unit/log/output.test.ts
Before, only the error name was rendered. Follow-up on #320
> fix: improve log errors

- app/(dashboard)/dashboard/types.ts
- eslint.config.js
- eslint/require-zod-schema-types.js
- hooks/use-toast.ts
- lib/db/schema.ts
- packages/shortest/src/ai/client.ts
- packages/shortest/src/browser/core/bash-tool.ts
- packages/shortest/src/core/runner/index.ts
- packages/shortest/src/log/config.ts
- packages/shortest/src/types/browser.ts
- packages/shortest/src/types/test.ts
- packages/shortest/src/utils/add-to-env.ts
- packages/shortest/src/utils/add-to-gitignore.ts
- packages/shortest/src/utils/errors.ts
- packages/shortest/tsconfig.json
Add a custom ESLint rule that enforces using Zod schemas for runtime type validation.
- Add `require-zod-schema-types` ESLint rule
- Configure rule to exempt React and Drizzle ORM types
- Add `eslint-disable` comments for existing type-only definitions
- Include vitest.config.ts in TypeScript project
- Ensures consistent runtime type validation by requiring Zod schemas
- Enforces new code moving forward uses Zod schema
- Prevents type-only types that lack runtime validation
- Convert existing type-only definitions to Zod schemas
- Extend rule to enforce Zod over interfaces
> feat(eslint): enforce Zod schema types

- packages/shortest/src/browser/core/browser-tool.ts
- packages/shortest/src/cli/bin.ts
- packages/shortest/src/core/runner/index.ts
- packages/shortest/src/index.ts
- packages/shortest/src/types/config.ts
- packages/shortest/src/utils/config.ts
- packages/shortest/tests/e2e/index.ts
- packages/shortest/tests/e2e/test-ai.ts
- packages/shortest/tests/e2e/test-email-rendering.ts
- packages/shortest/tests/e2e/test-github-login.ts
- packages/shortest/tests/e2e/test-keyboard.ts
- packages/shortest/tests/unit/config.test.ts
- packages/shortest/tests/unit/initialize-config.test.ts
Simplify usage of CLI arguments by merging them into the user config schema, which is then properly validated
* Part of issue #287 
* It simplifies the logic working with CLI arguments.
* Leverages Zod's validation as the source of truth of all the config values passed by the user, regardless if are coming via the CLI, or the config file
> feat(cli): merge CLI options into config

- packages/shortest/src/cli/bin.ts
- packages/shortest/src/core/runner/index.ts
- packages/shortest/src/types/config.ts
- packages/shortest/src/utils/errors.ts
- packages/shortest/tests/unit/config.test.ts
- packages/shortest/tests/unit/initialize-config.test.ts
* Make `config.testPattern` optional, default to `**/*.test.ts`
* Improve test runner error handling
* Improve CLI help output formatting and organization
* One step closer towards zero-config
* Reduce complexity and technical debt around error handling and default values
> feat: make config.testPattern optional

- package.json
- packages/shortest/package.json
- packages/shortest/src/ai/client.ts
- packages/shortest/src/browser/actions/index.ts
- packages/shortest/src/cache/test-cache.ts
- packages/shortest/src/core/runner/index.ts
- packages/shortest/src/core/runner/test-reporter.ts
- packages/shortest/src/utils/errors.ts
- packages/shortest/tests/unit/ai/client.test.ts
- pnpm-lock.yaml
* Bump Vercel AI SDK packages for both Next.js and Shortest
* Improve click animation handling with proper timing
* Add better error handling with typed cache errors
* Fix cursor position tracking in browser tool
* Clean up test cache file deletion logic
* Add trace logging for test start/end events
* Refactor error types using Zod enums
* Attempt to fix https://github.com/anti-work/shortest/issues/285
* While the test run now gracefully falls back to executing the test in normal mode, the actual caching mismatch may still be an issue that requires a deeper (reproducible on our `Log in` test for the Next.js app)
* Reduce coupling between `executeTest` and `runCachedTest` by encapsulating all cache-related logic in `runCachedTest`
> fix: improve test cache execution with fallback to normal mode

- packages/shortest/src/core/compiler/index.ts
Prevent "undefined in ES module scope" errors in type:module projects
Error when running Shortest on Flexile
> fix: ES Module compatibility for dirname

- packages/shortest/src/ai/client.ts
- packages/shortest/src/browser/actions/index.ts
- packages/shortest/src/browser/core/bash-tool.ts
- packages/shortest/src/browser/core/browser-tool.ts
- packages/shortest/src/browser/core/index.ts
- packages/shortest/src/browser/integrations/github.ts
- packages/shortest/src/browser/integrations/mailosaur.ts
- packages/shortest/src/browser/manager/index.ts
- packages/shortest/src/cache/test-cache.ts
- packages/shortest/src/cli/bin.ts
- packages/shortest/src/cli/init/index.ts
- packages/shortest/src/core/runner/index.ts
- packages/shortest/src/index.ts
- packages/shortest/src/log/index.ts
- packages/shortest/src/log/log.ts
- packages/shortest/src/log/output.ts
- packages/shortest/src/types/test.ts
- packages/shortest/src/utils/errors.ts
- packages/shortest/src/utils/platform.ts
- packages/shortest/tests/unit/ai/client.test.ts
- packages/shortest/tests/unit/config.test.ts
- packages/shortest/tests/unit/log/log.test.ts
* Add `ShortestError` base class with specialized error types
* Implement `asShortestError()` utility for error conversion
* Standardize error messages and formatting
* Use `ConfigError` for invalid `config` for `Log`
* Improves error reporting with consistent formatting
* Makes error handling more predictable
* Provides clearer error types for debugging
* Prevent catching non-Shortest errors
> feat: improve error handling

- packages/shortest/src/ai/client.ts
- packages/shortest/src/ai/tools/anthropic/bash_20241022.ts
- packages/shortest/src/ai/tools/anthropic/computer_20241022.ts
- packages/shortest/src/ai/tools/custom/check_email.ts
- packages/shortest/src/ai/tools/custom/github_login.ts
- packages/shortest/src/ai/tools/custom/navigate.ts
- packages/shortest/src/ai/tools/custom/run_callback.ts
- packages/shortest/src/ai/tools/custom/sleep.ts
- packages/shortest/src/browser/core/browser-tool.ts
- packages/shortest/src/core/runner/index.ts
- packages/shortest/src/tools/index.ts
- packages/shortest/src/tools/tool-registry.ts
- packages/shortest/src/types/browser.ts
- packages/shortest/src/types/config.ts
- packages/shortest/tests/unit/config.test.ts
- packages/shortest/tests/unit/tools/index.test.ts
- packages/shortest/tests/unit/tools/tool-registry.test.ts
Implement a comprehensive refactoring of the AI tools system  
* Create a modular tool system with a central ToolRegistry class
* Move tools from hardcoded implementation in AIClient to dedicated files
* Implement tool registration through createToolRegistry()
* Map Anthropic's computer actions to internal actions
In preparation for adding Claude 3.7.
Ref https://github.com/anti-work/shortest/pull/369#issuecomment-2691388346
> refactor: add ToolRegistry

- packages/shortest/src/browser/manager/index.ts
- packages/shortest/src/types/config.ts
- packages/shortest/tests/unit/config.test.ts
- packages/shortest/tests/unit/initialize-config.test.ts
Adds browser.contextOptions to pass custom [Playwright browser context options](https://playwright.dev/docs/test-use-options#more-browser-and-context-options).
* Allows configuring browser behavior (ignore HTTPS errors, permissions, geolocation)
* Apply options when initializing browser context
> feat: add config.browser options

- packages/shortest/src/core/runner/test-file-parser.ts
fix: #381 
@babel/traverse is a CommonJS module,
which is being imported into ESM, 
hence its exports structure becomes { default: { default: Function } }
We need to access the nested default export and use the commonjs require approach
> fix(cli): execute test with line no functionality

- packages/shortest/src/core/runner/index.ts
- packages/shortest/src/core/runner/test-reporter.ts
- packages/shortest/src/core/runner/test-run.ts
- packages/shortest/tests/unit/core/runner/test-run.test.ts
In preparation for https://github.com/antiwork/shortest/pull/387
Extract test execution state management into a dedicated `TestRun` class, replacing the previous `TestResult` type. This improves encapsulation of test state transitions (pending -> running -> passed/failed) and token usage tracking.
In #387, `TestRun` will be used to set the timestamp when the test runs starts, so that can it can be used to store screenshots in a folder having the same name as the test run cache file.
> chore(cli): replace TestResult with TestRun

- packages/shortest/package.json
- packages/shortest/scripts/build-cli.js
- packages/shortest/src/cli/bin.ts
- packages/shortest/src/cli/commands/detect-framework.ts
- packages/shortest/src/cli/commands/github-code.ts
- packages/shortest/src/cli/commands/index.ts
- packages/shortest/src/core/framework-detector/index.ts
- pnpm-lock.yaml
> [!NOTE]
> Experimental feature
Generates `.shortest/project.json` with framework information about the project/repo.
`data` is generated via [`@netlify/framework-info`](https://www.npmjs.com/package/@netlify/framework-info). Future work can improve/simplify, if this solution will stay.
Sample
```json
{
"metadata": {
"timestamp": 1742593873821,
"version": 1,
"git": {
"branch": "rmarescu/framework",
"commit": "995e002ed7ff7e5375ccd4a3258df06a5dced845"
}
},
"data": [
{
"id": "next",
"name": "Next.js",
"package": {
"name": "next",
"version": "15.0.0-canary.152"
},
"category": "static_site_generator",
"dev": {
"commands": [
"npm run dev",
"npm run start",
"npm run build"
],
"port": 3000,
"pollingStrategies": [
{
"name": "TCP"
}
]
},
"build": {
"commands": [
"next build"
],
"directory": …
```
> feat: add detect-framework command

- packages/shortest/src/cli/bin.ts
- packages/shortest/src/cli/commands/index.ts
- packages/shortest/src/cli/commands/plan.ts
- packages/shortest/src/core/test-planner/index.ts
- packages/shortest/src/core/test-planner/system-prompt.ts
> [!NOTE]
> Experimental feature
Follow-up on https://github.com/antiwork/shortest/pull/402
New command `npx shortest plan`
Generates `.shortest/{framework}/test-plan.json`. Uses AI to generate up to 10 test plans based on the `analysis.json` file
Sample [test-plan.json](https://gist.github.com/rmarescu/3457f144757875456d34af417a66468a)
> feat: add plan command

- packages/shortest/package.json
- packages/shortest/scripts/build-cli.js
- packages/shortest/src/cli/commands/analyze.ts
- packages/shortest/src/cli/commands/generate.ts
- packages/shortest/src/cli/commands/init.ts
- packages/shortest/src/cli/commands/init/generate-config-file.ts
- packages/shortest/src/cli/commands/plan.ts
- packages/shortest/src/core/app-analyzer/index.ts
- packages/shortest/src/core/app-analyzer/next-js-analyzer.ts
- packages/shortest/src/core/app-analyzer/types.ts
- packages/shortest/src/core/framework-detector/index.ts
- packages/shortest/src/core/test-generator/index.ts
- packages/shortest/src/core/test-generator/utils/lint-code.ts
- packages/shortest/src/core/test-planner/index.ts
- packages/shortest/src/log/log.ts
- packages/shortest/src/log/output.ts
- packages/shortest/src/types/config.ts
- packages/shortest/src/utils/env-file.ts
- packages/shortest/src/utils/get-git-info.ts
- packages/shortest/tests/unit/log/log.test.ts
- packages/shortest/tests/unit/log/output.test.ts
- pnpm-lock.yaml
Enhanced CLI initialization with interactive prompts for sample test generation, config customization, API key setup, and login credentials to streamline user onboarding with guided setup flow.
Ref https://github.com/antiwork/shortest/discussions/375#discussioncomment-12559992
The test file was not properly formatted due to some issues with detecting the ESLint config (no padding lines between  statements)
https://github.com/user-attachments/assets/b1f28e64-1ea6-431d-ab85-334e0ec964c8
Shortest is already installed on the project
https://github.com/user-attachments/assets/c821c16b-8043-4056-9efa-1a9f1d5da9f1
> feat: add sample test file generation to init command

- packages/shortest/src/tools/tool-registry.ts
- packages/shortest/src/types/config.ts
- packages/shortest/tests/unit/config.test.ts
- packages/shortest/tests/unit/initialize-config.test.ts
This PR adds support for Claude 4 models and sets Claude 4 Sonnet as the new default model. Adds claude-4-sonnet-20250514, claude-4-sonnet-latest, claude-4-opus-20250514, claude-4-opus-latest models. Updates AnthropicModelFamily to include claude-4. Sets claude-4-sonnet-20250514 as new default model. Updates tool version mappings for Claude 4 models. Updates all related tests. All unit tests pass and CLI builds successfully. Closes #447
> feat(ai): Add Claude 4 model support and set as default
