antiwork/shortest

app/(dashboard)/dashboard/pull-request.test.tsx

Cover the pull-request.tsx with tests

cover pull-request.tsx with tests

---

README.md

Clerk Social Connections tab is now named SSO Connections.

Updated README.md Github OAuth section

---

app/(dashboard)/dashboard/pull-request.test.tsx
app/(dashboard)/dashboard/pull-request.tsx
app/(dashboard)/dashboard/types.ts
lib/github.ts

Couldn't change the hardcoded commit name "Update test files" so I make it custom before "Commit changes" with keeping the default value "Update test files".

Being able to write custom commits

---

app/(dashboard)/dashboard/pull-request.test.tsx
app/(dashboard)/dashboard/pull-request.tsx
app/api/generate-tests/route.ts
app/api/generate-tests/schema.ts

Implements https://github.com/gumroad/shortest/issues/32
Reference: https://sdk.vercel.ai/examples/next-pages/basics/streaming-object-generation
https://github.com/user-attachments/assets/418d048c-5907-49e2-800a-80aaa342779b

Implement streaming

---

.github/workflows/shortest.yml
README.md
packages/shortest/package.json
packages/shortest/src/ai/ai.ts
packages/shortest/src/cli/bin.ts
packages/shortest/src/core/runner.ts
packages/shortest/src/types/index.ts
pnpm-lock.yaml
shortest.config.ts

Add a new Github workflow to run shortest test after a successful deployment in Vercel Preview env
Add two new command line args to override config file:
1.  --target=url to set the preview url 
2.  --headless to enforce headless mode in github workflow
Fix some bug and add command log validators
Remember to add ANTHROPIC_API_KEY key in github secrets.
Instructions in README.md file

Run Shortest in GitHub workflow

---

.github/workflows/publish.yml
app/__tests__/assert.test.ts
app/__tests__/home.test.ts
app/__tests__/login.test.ts
package.json
packages/shortest/CHANGELOG.md
packages/shortest/package.json
pnpm-lock.yaml
shortest.config.ts

Add workflow dispatch option to run publish action manually 
Added npm token check step
Added .npmrc creation
Added --frozen-lockfile to pnpm install
Kept the npm token check before publish
Update shortest package release date

Chore: Improvement to publish workflow

---

.gitignore
README.md
package.json
packages/shortest/.npmignore
packages/shortest/CHANGELOG.md
packages/shortest/README.md
packages/shortest/package.json
pnpm-lock.yaml
test-cli/package-lock.json
test-cli/package.json

v0.0.6 - Addresses Issue #109 
- Fixed Cli installation issues
- Updated README with more detailed instructions
- Added a new test folder specifically for simulating testing of shortest cli in prod like env

Fix Cli issue

---

packages/shortest/CHANGELOG.md
packages/shortest/package.json
packages/shortest/src/core/runner/index.ts

shortest v0.0.7
This PR addressers issue #111 
- Fixed hooks context not being reset between tests
- Updated docs and change logs
- bumped version

Bug: page context error

---

app/__tests__/dashboard.test.ts
app/__tests__/login.test.ts

update test files to use new shortest

udpate tests

---

packages/shortest/CHANGELOG.md
packages/shortest/package.json
packages/shortest/src/browser/actions/index.ts
packages/shortest/tests/test-keyboard.ts

This error came up in Iffy: 
- Fixed page up and page down action
- Add new test script for keyboard shortcuts
- Bump version and update changelogs

Bug: Fix page down and up action

---

README.md

Update docs to include instruction to pull the env vars from Vercel

update docs to include instruction to pull the env vars from Vercel

---

.github/workflows/autofix.yml
app/(dashboard)/page.tsx
app/api/github/webhook/route.ts
app/api/stripe/checkout/route.ts
eslint.config.js
hooks/use-toast.ts
lib/db/seed.ts
lib/github.ts
lib/setup.ts
package.json
packages/shortest/src/ai/client.ts
packages/shortest/src/browser/core/browser-tool.ts
packages/shortest/src/browser/integrations/github.ts
packages/shortest/src/cli/setup.ts
packages/shortest/src/core/builder/index.ts
packages/shortest/src/core/compiler/index.ts
packages/shortest/src/core/runner/index.ts
packages/shortest/src/index.ts
packages/shortest/src/types/config.ts
packages/shortest/tests/test-ai.ts
packages/shortest/tests/test-assertion.ts
pnpm-lock.yaml

This PR addresses Issue: #182 
Copied the Autofix workflow from Iffy. 
Changed it to use pnpm instead of npm

Add autofix

---

packages/shortest/src/core/runner/index.ts

Following the discussion in https://github.com/anti-work/shortest/pull/136#issuecomment-2566632879
I made this adjustment to expect the test to be successful.
please let me know your thoghts

adjust the prompt to expect the test to be successful

---

README.md
packages/shortest/README.md

Removed support from yarn for now. Although installation works, there are some issues with resolving peer-dependencies in yarn.

remove yarn support

---

README.md
packages/shortest/README.md

Issue #244 
In prepration for release of v0.4.0, we need to update the README that will be shown in npm website.

Update npm readme

---

packages/shortest/CHANGELOG.md
packages/shortest/package.json

Issue #244 
To avoid pushing directly to main, created this PR.
Bumped the version 
Updated Changlogs for npm (Trying a new style with mentioning the names of the contributors and their PRs)

Release Version 0.4.0

---

README.md
packages/shortest/src/ai/client.ts
packages/shortest/src/core/runner/index.ts
packages/shortest/src/utils/logger.ts

* Show if a particular test was executed from the cache with a boolean flag

feat(logger): add token usage details in summary

---

README.md
packages/shortest/README.md

* Change step 2 in the Quick State section to follow the file with test pattern instead of test directory

docs: update `Quick start` steps 

---

packages/shortest/src/core/runner/index.ts

fix(cli): Handle browser initialization failure

---

packages/shortest/src/ai/client.ts

fix(cli): prevent AI API retries for select status codes

---

packages/shortest/package.json
packages/shortest/src/browser/core/browser-tool.ts
packages/shortest/src/cli/bin.ts
packages/shortest/src/core/compiler/index.ts
packages/shortest/src/core/runner/index.ts
packages/shortest/src/index.ts
packages/shortest/src/types/config.ts
packages/shortest/src/utils/config.ts
packages/shortest/src/utils/errors.ts
packages/shortest/tests/test-ai.ts
packages/shortest/tests/test-browser.ts
packages/shortest/tests/test-config.ts
packages/shortest/tests/test-email.ts
packages/shortest/tests/test-github.ts
packages/shortest/tests/test-initialize-config.ts
packages/shortest/tests/test-keyboard.ts
packages/shortest/tests/test-loop.ts
packages/shortest/vitest.config.ts
pnpm-lock.yaml

* Introduce Zod
* Config test coverage with vitest
* Improved error handling

chore(cli): Improve config parsing and validation

---

app/(dashboard)/page.test.ts
packages/shortest/src/ai/client.ts
packages/shortest/src/ai/prompts/index.ts
packages/shortest/src/browser/core/bash-tool.ts
packages/shortest/src/browser/core/browser-tool.ts
packages/shortest/src/browser/manager/index.ts
packages/shortest/src/cache/cache.ts
packages/shortest/src/cli/bin.ts
packages/shortest/src/core/runner/index.ts
packages/shortest/src/core/runner/test-reporter.ts
packages/shortest/src/index.ts
packages/shortest/src/types/ai.ts
packages/shortest/src/types/test.ts
packages/shortest/tests/e2e/test-ai.ts
packages/shortest/tests/e2e/test-browser.ts
packages/shortest/tests/e2e/test-email-rendering.ts
packages/shortest/tests/e2e/test-github-login.ts
packages/shortest/tests/e2e/test-keyboard.ts
packages/shortest/tests/e2e/test-loop.ts

Part of https://github.com/anti-work/shortest/issues/286 and in preparation for https://github.com/anti-work/shortest/pull/320
Extracts code from that PR to reduce the diff and reduce possible merge conflicts. No real functional change was introduced.

refactor: prepare TestReporter

---

packages/shortest/src/browser/core/browser-tool.ts
packages/shortest/src/cache/test-cache.ts
packages/shortest/src/cli/bin.ts
packages/shortest/src/core/builder/index.ts
packages/shortest/src/core/runner/index.ts
packages/shortest/src/core/runner/test-case.ts
packages/shortest/src/core/runner/test-reporter.ts
packages/shortest/src/index.ts
packages/shortest/src/types/cache.ts
packages/shortest/src/types/globals.ts
packages/shortest/src/types/test.ts
packages/shortest/tests/e2e/test-ai.ts
packages/shortest/tests/unit/cache/test-cache.test.ts
packages/shortest/tests/unit/core/runner/test-case.test.ts

Adds structured `TestCase` model replacing `TestFunction` type, with formal validation and better test registry management. Improved test cache and error handling.

chore: add TestCase

---

bug/sample.test.ts
packages/shortest/src/ai/client.ts
packages/shortest/src/core/runner/index.ts
packages/shortest/src/core/runner/test-run-repository.ts
packages/shortest/src/core/runner/test-run.ts
packages/shortest/src/types/cache.ts
packages/shortest/tests/e2e/test-ai.ts
packages/shortest/tests/e2e/test-browser.ts
packages/shortest/tests/e2e/test-email-rendering.ts
packages/shortest/tests/e2e/test-github-login.ts
packages/shortest/tests/e2e/test-keyboard.ts
packages/shortest/tests/unit/ai/client.test.ts
packages/shortest/tests/unit/cache/index.test.ts
packages/shortest/tests/unit/core/runner/test-run-repository.test.ts
packages/shortest/tests/unit/core/runner/test-run.test.ts

fix: test run uses existing cache
